server:
  port: 8089

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

redis:
  sdk:
    config:
      host: 123.57.226.115
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

zookeeper:
  sdk:
    config:
      connect-string: 123.57.226.115:2181
      base-sleep-time-ms: 1000
      max-retries: 3
      session-timeout-ms: 18000
      connection-timeout-ms: 30000

# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
        redis:
          # 状态；true = 开启、false 关闭
          enabled: false
          # redis host
          host: 123.57.226.115
          # redis port
          port: 16379
        zookeeper:
          # 状态；true = 开启、false 关闭
          enabled: true
          # zookeeper
          connect-string: 123.57.226.115:2181

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
